### ISSUE TITLE
Improve CSP UX

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/hugo-module-tnd-headers#1]
CSPs can get complex and are error prone. There are many possible directives, not all of which will have values.

This document contains the syntax and all possible examples:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

While many elements of security headers are static over time, it's important to keep in mind for UX that this is a LIVING policy, subject to change as scripts and services are added to the site. 

This is an RL example that lays out what I think will reduce errors as we add values over time. The actual layout is less important than the idea that each value gets its own "entry," so to speak.

Note also. Any values that are not URIs must have single quote marks around them, which my example does not reflect because I formatted the YAML (a potential source of errors)

```
- values:
    - key: Content-Security-Policy
      value:
        - default-src:
            - "self"
        - script-src:
            - "self"
            - "unsafe-eval"
            - https://cdn.usefathom.com
            - https://identity.netlify.com
            - https://unpkg.com;
        - style-src:
            - "self"
            - "unsafe-inline"
        - prefetch-src:
            - https://thenewdynamic.imgix.net
        - object-src:
            - "none"
        - img-src:
        - "self"
        - https://thenewdynamic.imgix.net
        - https://img3.usefathom.com;
        - font-src:
        - "self"
        - base-uri:
        - "none"
        - connect-src:
            - "self"
            - https://cdn.usefathom.com
    - key: Strict-Transport-Security
      value: max-age=15768000
```

***
references:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
