### ISSUE TITLE
Set some sensible defaults

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/hugo-module-tnd-headers#5]
I think these headers could be set as defaults, so that they do not need to be set in the user's repo. I also think we can have a set of defaults for Content Security Policy, but I don't have that prepared yet.
```
- headers:
     - field: Strict-Transport-Security
       value: max-age=31536000
     - field: X-Xss-Protection
       value: 1; mode=block
     - field: X-Frame-Options
       value: DENY
     - field: X-Content-Type-Options
       value: nosniff
     - field: Referrer-Policy
       value: strict-origin-when-cross-origin
     - field: Feature-Policy
       value: camera 'none'; geolocation 'none'; microphone 'none' 
```
